[workspace]
resolver = "2"
members = [
    "ch01",
    "ch02",
    "ch03",
    "ch04",
    "ch05",
    "ch06",
    "ch07",
    "ch08",
    "ch09",
    "ch10",
    "ch11",
    "ch12",
    "ch13",
    "ch14",
    "ch15",
    "ch16",
    "ch16_mo_rong",
    "ch17",
    "ch18",
    "ch19",
    "ch20",
    "ch21",
    "ch22",
    "ch23",
    "ch24",
    "ch25",
    "ch26",
    "ch27",
    "ch28",
    "ch29",
    "ch30",
    "ch31",
    "ch32",
    "ch33",
    "ch34",
    "ch35",
    "ch36",
    "ch37",
    "ch38",
    "ch39",
    "ch40",
    "ch41",
    "ch42",
    "ch43",
    "ch44",
    "ch45",
    "ch46",
    "ch47",
    "ch48",
    "ch49",
    "ch50",
    "ch51",
    "ch52",
    "ch53",
    "ch54",
    "ch55",
    "ch56",
    "ch57",
    "ch58",
    "ch59",
    "ch60",
    "ch61",
    "ch62",
    "ch63",
    "ch64",
    "ch65",
    "ch66",
    "ch67",
    "ch68",
    "ch69",
    "ch70",
    "ch71",
    "ch72",
    "ch73",
    "ch74",
    "ch75",
    "ch76",
    "ch77",
    "ch78",
    "ch79",
    "ch80",
    "ch81",
    "ch82",
    "ch83",
    "ch84",
    "ch85",
    "phu_luc_a",
]
